[package]
name = "rpc2_plugin_workspacefs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
abi_stable = "0.11.3"
dirs = "5.0.1"
rpc2_interface = { version = "0.1.0", path = "../interface" }
serde_json = "1.0.133"
